version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - .:/mailling
    depends_on:
      - db
      - worker

  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=your_username
      - POSTGRES_PASSWORD=your_password
      - POSTGRES_DB=your_database_name

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/mailling
    depends_on:
      - db
    command: celery -A your_project_name worker --loglevel=info
